version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    container_name: pushups-backend
    networks:
      - pushups-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    container_name: pushups-frontend
    environment:
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000/ws/process-video
    depends_on:
      - backend
    networks:
      - pushups-network

networks:
  pushups-network:
    driver: bridge 